# Generated by Django 3.2 on 2021-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'doing']},
        ),
        migrations.AddField(
            model_name='task',
            name='doing',
            field=models.BooleanField(default=False),
        ),
    ]
